### ISSUE TITLE
Do we need the intermediate fabric subpackage?

### ISSUE THREAD

**Issue by Lawouach** [chaostoolkit-incubator/chaostoolkit-service-fabric#4]
I wonder if the probes and actions couldn't live at the top of the package rather than under the fabric/ directory?

Is there a need for that sub-directory?

cc @buderre 

I will release a first version once we have made a decision here.

**Comment by buderre** [comment]
More fine granular commands are **theoretically** possible for the Service Fabric. [This](https://docs.microsoft.com/de-de/python/api/azure-servicefabric/azure.servicefabric.operations.mesh_application_operations.meshapplicationoperations?view=azure-python) is one example for such a command. Keeping this in mind, it could be interesting to have sub-directories for them.

Looking at the [start_chaos](https://docs.microsoft.com/de-de/python/api/azure-servicefabric/azure.servicefabric.service_fabric_client_ap_is.servicefabricclientapis?view=azure-python#start-chaos-chaos-parameters--timeout-60--custom-headers-none--raw-false----operation-config-) operation the Microsoft team put them in the **cluster** package. My suggestion would be to rename the **fabric** package to **cluster**.

@mkaszub can you add some valueable insight from your experience with the Service Fabric?

**Comment by Lawouach** [comment]
Should I go ahead and rename that directory you think?

**Comment by buderre** [comment]
@Lawouach : I would say yes. Let's addict to the Microsoft naming and stay synch with the package *cluster*. Additionally having in mind that we can extend it later for other actions.

**Comment by mkaszub** [comment]
@Lawouach @buderre 
Keeping it in subfolder and renaming it to "cluster" make sense for me. As Bugra mentioned we can add additional actions which injects chaos in more controller fashioned e.g disable/enable nodes

**Comment by Lawouach** [comment]
Thanks folks. Fixed and released

https://pypi.org/project/chaostoolkit-service-fabric/
